version: '3.7'

services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webpack:
    build: .
    command: ruby ./bin/webpack-dev-server
    ports:
      - 3035:3035
    container_name: webpack
    volumes:
      - .:/app

  web:
    build: .
    command: bundle exec pumactl start
    ports:
      - 80:3000
    container_name: web
    volumes:
      - .:/app
    depends_on:
      - webpack
    tty: true
    stdin_open: true

volumes:
  postgres-data:
    driver: local
